DEFINE 
// FxTituloGraficos 
    FUNCTION fxRotuloGrfc = ( amount : NUMERIC ) => 
    IF(
        amount > 0 ,
        SWITCH(
            TRUE(),
            amount >= 1e6, "€ #,#0,,.00M",
            amount >= 1e3, "€ #,#0,.00K",
            "€ #,#0.00" 
        ),
        SWITCH(
            TRUE(),
            ABS( amount ) >= 1e6, "(€ #,#0,,.00M)",
            ABS( amount ) >= 1e3, "(€ #,#0,.00K)",
            "(€ #,#0.00)" )
        )
// FxCaixas
    FUNCTION fxCaixas = ( amount : NUMERIC ) => 
    IF(
        amount > 0 ,
        SWITCH(
            TRUE(),
            amount >= 1e6, "#,#0,,.00M",
            amount >= 1e3, "#,#0,.00K",
            "#,#0.00" 
        ),
        SWITCH(
            TRUE(),
            ABS( amount ) >= 1e6, "(#,#0,,.00M)",
            ABS( amount ) >= 1e3, "(#,#0,.00K)",
            "(#,#0.00)" )
        )

// fx SELECT
    FUNCTION fxSELECT = ( selectt : int64) =>
        SWITCH(
                selectt,
                0, [Total ImpBruto],
                1, [Total ImpNeto],
                2, [Total Docenas/OK],
                3, [Precio neto/docena],
                4, [Indice inprovo Ponderado] )

