DEFINE 
// FxTituloGraficos 
    FUNCTION fxRotuloGrfc = ( amount : NUMERIC ) => 
    IF(
        amount > 0 ,
        SWITCH(
            TRUE(),
            amount >= 1e6, "€ #,#0,,.00M",
            amount >= 1e3, "€ #,#0,.00K",
            "€ #,#0.00" 
        ),
        SWITCH(
            TRUE(),
            ABS( amount ) >= 1e6, "(€ #,#0,,.00M)",
            ABS( amount ) >= 1e3, "(€ #,#0,.00K)",
            "(€ #,#0.00)" )
        )
// FxCaixas
    FUNCTION fxCaixas = ( amount : NUMERIC ) => 
    IF(
        amount > 0 ,
        SWITCH(
            TRUE(),
            amount >= 1e6, "#,#0,,.00M",
            amount >= 1e3, "#,#0,.00K",
            "#,#0.00" 
        ),
        SWITCH(
            TRUE(),
            ABS( amount ) >= 1e6, "(#,#0,,.00M)",
            ABS( amount ) >= 1e3, "(#,#0,.00K)",
            "(#,#0.00)" )
        )