table 'Medias Inprovo'
	lineageTag: d8476d2f-cb8e-4dfd-b183-9be0a4045767

	column SEMANA
		dataType: string
		lineageTag: 31d3357e-6063-4261-88db-abcfa252b751
		summarizeBy: none
		sourceColumn: SEMANA

		annotation SummarizationSetBy = Automatic

	column 'SUELO_''L'
		dataType: double
		lineageTag: ce7de868-156b-4111-ba9c-9753440e0d12
		summarizeBy: sum
		sourceColumn: SUELO_'L

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SUELO_''M'
		dataType: double
		lineageTag: 8665b401-89cc-4603-94f9-c58c0fa8a89b
		summarizeBy: sum
		sourceColumn: SUELO_'M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ECOLOGICO_ L/24'
		dataType: double
		lineageTag: a5e950e4-b957-4514-b8d1-aae66f62bda0
		summarizeBy: sum
		sourceColumn: ECOLOGICO_ L/24

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ECOLOGICO_M/24
		dataType: double
		lineageTag: 9a30437e-6e98-4f25-9cb3-a8270cca809d
		summarizeBy: sum
		sourceColumn: ECOLOGICO_M/24

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column JAULA_L
		dataType: double
		lineageTag: 86fc743a-4401-480d-b2e5-83203a4ae36e
		summarizeBy: sum
		sourceColumn: JAULA_L

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'JAULA _M'
		dataType: double
		lineageTag: ff8db82b-52a4-47e9-bc7f-cc0de026569e
		summarizeBy: sum
		sourceColumn: JAULA _M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5944bb38-8001-4e0d-bd62-ae3205b04875
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Atributo
		dataType: string
		lineageTag: 7e943437-89db-4173-b297-78729e184913
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 2b729064-57c6-49ba-8be4-2b5110aa3c89
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Medias Inprovo' = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\Users\bruno.silva\Documents\bruno\PBXs\Exterior\Espanha\Dados\Medias Inprovo"),
				    #"Personalização Adicionada" = Table.AddColumn(Fonte, "Table", each Excel.Workbook([Content],true){[Name="MEDIAS "]}[Data]),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada", each ([Extension] = ".xls")),
				    #"Table Expandido" = Table.ExpandTableColumn(#"Linhas Filtradas", "Table", {"F1", "SEMANA", "SUELO_'L", "SUELO_'M", "MEDIA SUELO", "CAMPERO_", "ECOLOGICO_ L/24", "ECOLOGICO_M/24", "MEDIA ECOLOGICO", "JAULA_L", "JAULA _M", "MEDIA JAULA (DOCENA )", "JAULA INDUSTRIA (€/K)", "F14", "F15"}, {"F1", "SEMANA", "SUELO_'L", "SUELO_'M", "MEDIA SUELO", "CAMPERO_", "ECOLOGICO_ L/24", "ECOLOGICO_M/24", "MEDIA ECOLOGICO", "JAULA_L", "JAULA _M", "MEDIA JAULA (DOCENA )", "JAULA INDUSTRIA (€/K)", "F14", "F15"}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Table Expandido",{"SEMANA", "SUELO_'L", "SUELO_'M", "MEDIA SUELO", "CAMPERO_", "ECOLOGICO_ L/24", "ECOLOGICO_M/24", "MEDIA ECOLOGICO", "JAULA_L", "JAULA _M", "MEDIA JAULA (DOCENA )", "JAULA INDUSTRIA (€/K)"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Outras Colunas Removidas", each ([SEMANA] <> null and [SEMANA] <> "19,39" and [SEMANA] <> "MEDIA") and ([#"SUELO_'L"] <> null)),
				    #"Função Personalizada Invocada" = Table.AddColumn(#"Linhas Filtradas1", "Date", each FxSemana([SEMANA])),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Função Personalizada Invocada",{{"Date", type date}, {"JAULA INDUSTRIA (€/K)", type number}, {"MEDIA JAULA (DOCENA )", type number}, {"JAULA _M", type number}, {"JAULA_L", type number}, {"MEDIA ECOLOGICO", type number}, {"ECOLOGICO_M/24", type number}, {"ECOLOGICO_ L/24", type number}, {"CAMPERO_", type number}, {"MEDIA SUELO", type number}, {"SUELO_'M", type number}, {"SUELO_'L", type number}, {"SEMANA", type text}}),
				    #"Outras Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Tipo Alterado", {"SEMANA","SUELO_'L", "SUELO_'M", "ECOLOGICO_ L/24", "ECOLOGICO_M/24", "JAULA_L", "JAULA _M","Date"}, "Atributo", "Valor")
				in
				    #"Outras Colunas Não Dinâmicas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

